AWSTemplateFormatVersion: "2010-09-09"

Description: Deploy lambda function for updateusersjsoncsv

Parameters:
  S3ArchiveBucket:
    Type: String
    Description: S3 bucket with compiled lambda code as a zip archive
  S3Key:
    Type: String
    Description: S3 zip file path relative to root of S3 bucket
  IAMRoleName:
    Type: String
    Description: IAM role with lambda execution permissions
  LambdaFunctionName:
    Type: String
    Description: Lambda Function Name
  LambdaFunctionDescription:
    Type: String
    Description: Lambda Function Description
  BUCKETNAME:
    Type: String
    Description: S3 Bucket Name
  TABLENAME:
    Type: String
    Description: DynamoDB TABLENAME
  BuildEnv:
    Type: String
    Description: Pipeline Build environment
Resources:
  DeployLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Description: !Ref LambdaFunctionDescription
      Handler: lambda_function.lambda_handler
      Role: !Ref "IAMRoleName"
      Runtime: python3.8
      Timeout: 900
      Environment:
        Variables:
          BUCKETNAME: !Ref BUCKETNAME
          tableName: !Ref TABLENAME
      Tags:
        - Key: LOB
          Value: "AdminSolution"
        - Key: Environment
          Value: !Ref BuildEnv
        - Key: Purpose
          Value: pipeline
        - Key: Creationsource
          Value: CFN
        - Key: Deploymentversion
          Value: "20220124"
        - Key: Project
          Value: LW-CC-Migration
      Code:
        S3Bucket: !Ref "S3ArchiveBucket"
        S3Key: !Ref "S3Key"
